name: my_pipeline

on: 
  push:
    branches: 
      - DEV 

jobs:
  My_First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11  # Choose a JDK version compatible with your project.
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # You can use other JDK distributions like 'zulu'.
          java-version: '11'  # Specify the JDK version.

      #- name: Cache Maven packages
        # uses: actions/cache@v3
        #with:
         # path: ~/.m2/repository
         # key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         # restore-keys: |
           # ${{ runner.os }}-maven-

      - name: build the code
        run: |
          mvn clean install -DskipTests
          ls -rlt .

      - name: copy JAR to s3 bucket
        run: |
          cp target/docker-demo-0.0.1-SNAPSHOT.jar s3://anubhav-github-actionv3/demo-folder/
