name: my_pipeline
on: 
  push:
     branches: 
        - DEV
jobs:
  My_First_Job:
       runs-on: ubuntu-latest
       steps:
       - name: checkout code
         uses: actions/checkout@v3	
       - name: Print working directory
         run: pwd
  Second_Job:
       runs-on: ubuntu-latest
       needs: My_First_Job
       steps:
       - name: build the code
         run: |
            mvn clean install -DskipTests
