name: my_pipeline_change
on: 
  push:
     branches: 
        - DEV
env:
  EC2_PEM_KEY: ${{ secrets.PRIVATE_KEY }}
jobs:
  Build_Copy_Job:
       runs-on: ubuntu-latest
       steps:
       - name: checkout code
         uses: actions/checkout@v3
       - name: setup jdk
         uses: actions/setup-java@v4
         with:
           java-version: '11'
           distribution: 'temurin'
           cache: maven
       - name: run maven
         run: mvn clean install -DskipTests
       - name: setup ssh keys
         run: |
           mkdir ~/.ssh/
           echo "${{ env.EC2_PEM_KEY }}" >> ~/.ssh/ec2-key.pem
           chmod 400 ~/.ssh/ec2-key.pem
           ssh-keygen -p -m PEM -f ~/.ssh/ec2-key.pem
       - name: scp to ec2
         run: |
            scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem target/*.jar ec2-user@ec2-3-94-123-21.compute-1.amazonaws.com:/home/ec2-user/data/jar/
