name: my_pipeline_change
on: 
  push:
     branches: 
        - DEV
jobs:
  Build_Copy_Job:
       runs-on: ubuntu-latest
       steps:
       - name: checkout code
         uses: actions/checkout@v3
       - name: setup jdk
         uses: actions/setup-java@v4
         with:
           java-version: '11'
           distribution: 'temurin'
           cache: maven
       - name: run maven
         run: mvn clean install -DskipTests
       - name: setup ssh keys
         run: |
           mkdir ~/.ssh/
           chmod -R 755 ~/.ssh/
           echo $EC2_PEM_KEY > ~/.ssh/ec2-key.pem
           chmod 600 ~/.ssh/ec2-key.pem
           cat ~/.ssh/ec2-key.pem
         env:
          EC2_PEM_KEY: ${{ secrets.PRIVATE_KEY }}
       - name: scp to ec2
         run: |
            scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem target/*.jar ec2-user@ec2-34-234-84-139.compute-1.amazonaws.com:/home/ec2-user/data/jar/
